## Importando as bibliotecas

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sweetviz as sv
import numpy as np
from sklearn import preprocessing
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)

## Leitura dos arquivos que compôe o dataset

### Base com informações sobre as empresas do Mercado a ser considerado.

In [2]:
market = pd.read_csv('estaticos_market.csv', sep=',', index_col=0)

### Ids dos clientes da empresa 1

In [3]:
empresa_1_ids = pd.read_csv('estaticos_portfolio1.csv', usecols=['id'])

### Ids dos clientes da empresa 2

In [4]:
empresa_2_ids = pd.read_csv('estaticos_portfolio2.csv', index_col=0)

### Ids dos clientes da empresa 3

In [5]:
empresa_3_ids = pd.read_csv('estaticos_portfolio3.csv', index_col=0)

### Função para saber mais sobre o dataframe

In [6]:
def exploracao(df):
    exploracao = pd.DataFrame({
        'coluna' : df.columns,
        'tipos' : df.dtypes,
        'qtd_null' : df.isnull().sum()
    })
    exploracao['percent_null'] = np.round((exploracao.qtd_null / df.shape[0]) * 100, 4)
    
    return exploracao.sort_values(by='qtd_null', ascending=False)

In [7]:
def filter_columns(df):
    df_exploracao = exploracao(market)
    features = df_exploracao[(df_exploracao.percent_null < 20.0)]['coluna']
    return df[features]

### Criando função para encode das strings

In [8]:
def encoding_obj(df, le):
    colunas_obj = df.columns[df.dtypes == object]
    df[colunas_obj] = df[colunas_obj].apply(lambda col: le.fit_transform(col))
    return df

### Definindo treino e teste do portfólio

In [9]:
def treino_teste_port(df):
    X_train, X_test, y_train, y_test = train_test_split(
    port_1_encode, list(range(len(port_1_encode))), test_size=0.3, random_state=1)
    return X_train, X_test

## EDA do Market

In [10]:
exploracao(market)

,coluna,tipos,qtd_null,percent_null
qt_alteracao_socio_total,qt_alteracao_socio_total,float64,462298,100.0000
qt_alteracao_socio_90d,qt_alteracao_socio_90d,float64,462298,100.0000
grau_instrucao_macro_desconhecido,grau_instrucao_macro_desconhecido,float64,462298,100.0000
qt_alteracao_socio_180d,qt_alteracao_socio_180d,float64,462298,100.0000
qt_alteracao_socio_365d,qt_alteracao_socio_365d,float64,462298,100.0000
coligada_mais_antiga_baixada,coligada_mais_antiga_baixada,float64,462162,99.9706
coligada_mais_nova_baixada,coligada_mais_nova_baixada,float64,462162,99.9706
idade_media_coligadas_baixadas,idade_media_coligadas_baixadas,float64,462162,99.9706
vl_total_veiculos_antt,vl_total_veiculos_antt,float64,462122,99.9619
vl_total_tancagem,vl_total_tancagem,float64,462018,99.9394
vl_total_veiculos_antt_grupo,vl_total_veiculos_antt_grupo,float64,461962,99.9273
vl_total_tancagem_grupo,vl_total_tancagem_grupo,float64,460538,99.6193
grau_instrucao_macro_analfabeto,grau_instrucao_macro_analfabeto,float64,460414,99.5925
idade_ate_18,idade_ate_18,float64,459392,99.3714
qt_socios_st_suspensa,qt_socios_st_suspensa,float64,459047,99.2968
vl_potenc_cons_oleo_gas,vl_potenc_cons_oleo_gas,float64,458615,99.2033
qt_socios_pj_baixados,qt_socios_pj_baixados,float64,457754,99.0171
qt_socios_pj_nulos,qt_socios_pj_nulos,float64,457754,99.0171
qt_socios_pj_suspensos,qt_socios_pj_suspensos,float64,457754,99.0171
qt_socios_pj_inaptos,qt_socios_pj_inaptos,float64,457754,99.0171
vl_idade_media_socios_pj,vl_idade_media_socios_pj,float64,457754,99.0171
vl_idade_minima_socios_pj,vl_idade_minima_socios_pj,float64,457754,99.0171
vl_idade_maxima_socios_pj,vl_idade_maxima_socios_pj,float64,457754,99.0171
qt_socios_pj_ativos,qt_socios_pj_ativos,float64,457754,99.0171
qt_art,qt_art,float64,455708,98.5745
qt_socios_pep,qt_socios_pep,float64,455555,98.5414
idade_acima_de_58,idade_acima_de_58,float64,451272,97.6150
idade_de_54_a_58,idade_de_54_a_58,float64,448323,96.9771
idade_de_49_a_53,idade_de_49_a_53,float64,443261,95.8821
total_filiais_coligados,total_filiais_coligados,float64,441898,95.5873
media_filiais_coligados,media_filiais_coligados,float64,441898,95.5873
max_filiais_coligados,max_filiais_coligados,float64,441898,95.5873
min_filiais_coligados,min_filiais_coligados,float64,441898,95.5873
grau_instrucao_macro_escolaridade_superior,grau_instrucao_macro_escolaridade_superior,float64,439571,95.0839
vl_frota,vl_frota,float64,438108,94.7674
idade_de_44_a_48,idade_de_44_a_48,float64,438008,94.7458
grau_instrucao_macro_escolaridade_fundamental,grau_instrucao_macro_escolaridade_fundamental,float64,437402,94.6147
idade_de_19_a_23,idade_de_19_a_23,float64,436408,94.3997
idade_de_39_a_43,idade_de_39_a_43,float64,431890,93.4224
vl_total_veiculos_leves,vl_total_veiculos_leves,float64,431614,93.3627
vl_total_veiculos_pesados,vl_total_veiculos_pesados,float64,431614,93.3627
vl_folha_coligados,vl_folha_coligados,float64,425984,92.1449
media_vl_folha_coligados,media_vl_folha_coligados,float64,425984,92.1449
max_vl_folha_coligados,max_vl_folha_coligados,float64,425984,92.1449
min_vl_folha_coligados,min_vl_folha_coligados,float64,425984,92.1449
media_vl_folha_coligados_gp,media_vl_folha_coligados_gp,float64,425761,92.0967
vl_folha_coligados_gp,vl_folha_coligados_gp,float64,425761,92.0967
min_vl_folha_coligados_gp,min_vl_folha_coligados_gp,float64,425761,92.0967
max_vl_folha_coligados_gp,max_vl_folha_coligados_gp,float64,425761,92.0967
idade_de_34_a_38,idade_de_34_a_38,float64,425569,92.0551
idade_de_24_a_28,idade_de_24_a_28,float64,423403,91.5866
idade_de_29_a_33,idade_de_29_a_33,float64,422155,91.3166
min_funcionarios_coligados_gp,min_funcionarios_coligados_gp,float64,419995,90.8494
max_funcionarios_coligados_gp,max_funcionarios_coligados_gp,float64,419995,90.8494
media_funcionarios_coligados_gp,media_funcionarios_coligados_gp,float64,419995,90.8494
qt_funcionarios_coligados_gp,qt_funcionarios_coligados_gp,float64,419995,90.8494
qt_funcionarios_coligados,qt_funcionarios_coligados,float64,419995,90.8494
de_indicador_telefone,de_indicador_telefone,object,418405,90.5055
sum_faturamento_estimado_coligadas,sum_faturamento_estimado_coligadas,float64,412754,89.2831
qt_coligadas,qt_coligadas,float64,412067,89.1345
min_faturamento_est_coligados,min_faturamento_est_coligados,float64,397775,86.0430
faturamento_est_coligados,faturamento_est_coligados,float64,397775,86.0430
max_faturamento_est_coligados,max_faturamento_est_coligados,float64,397775,86.0430
faturamento_est_coligados_gp,faturamento_est_coligados_gp,float64,397775,86.0430
media_faturamento_est_coligados_gp,media_faturamento_est_coligados_gp,float64,397775,86.0430
max_faturamento_est_coligados_gp,max_faturamento_est_coligados_gp,float64,397775,86.0430
min_faturamento_est_coligados_gp,min_faturamento_est_coligados_gp,float64,397775,86.0430
media_faturamento_est_coligados,media_faturamento_est_coligados,float64,397775,86.0430
coligada_mais_antiga_ativa,coligada_mais_antiga_ativa,float64,397151,85.9080
coligada_mais_nova_ativa,coligada_mais_nova_ativa,float64,397151,85.9080
idade_media_coligadas_ativas,idade_media_coligadas_ativas,float64,397151,85.9080
qt_coligados_exterior,qt_coligados_exterior,float64,396907,85.8552
qt_coligados_sudeste,qt_coligados_sudeste,float64,396907,85.8552
qt_coligados_centro,qt_coligados_centro,float64,396907,85.8552
qt_coligados_sul,qt_coligados_sul,float64,396907,85.8552
qt_coligados_nordeste,qt_coligados_nordeste,float64,396907,85.8552
qt_regioes_coligados,qt_regioes_coligados,float64,396907,85.8552
qt_ufs_coligados,qt_ufs_coligados,float64,396907,85.8552
qt_coligados_mei,qt_coligados_mei,float64,396907,85.8552
qt_ramos_coligados,qt_ramos_coligados,float64,396907,85.8552
qt_coligados_industria,qt_coligados_industria,float64,396907,85.8552
qt_coligados_agropecuaria,qt_coligados_agropecuaria,float64,396907,85.8552
qt_coligados_comercio,qt_coligados_comercio,float64,396907,85.8552
qt_coligados_serviço,qt_coligados_serviço,float64,396907,85.8552
qt_coligados_ccivil,qt_coligados_ccivil,float64,396907,85.8552
qt_coligados_epp,qt_coligados_epp,float64,396907,85.8552
qt_coligados_atividade_alto,qt_coligados_atividade_alto,float64,396907,85.8552
qt_coligados_atividade_medio,qt_coligados_atividade_medio,float64,396907,85.8552
qt_coligados_atividade_baixo,qt_coligados_atividade_baixo,float64,396907,85.8552
qt_coligados_atividade_mt_baixo,qt_coligados_atividade_mt_baixo,float64,396907,85.8552
qt_coligados_atividade_inativo,qt_coligados_atividade_inativo,float64,396907,85.8552
qt_coligados_norte,qt_coligados_norte,float64,396907,85.8552
idade_minima_coligadas,idade_minima_coligadas,float64,396907,85.8552
qt_coligados_ltda,qt_coligados_ltda,float64,396907,85.8552
qt_coligados_suspensa,qt_coligados_suspensa,float64,396907,85.8552
qt_coligados,qt_coligados,float64,396907,85.8552
qt_socios_coligados,qt_socios_coligados,float64,396907,85.8552
qt_coligados_matriz,qt_coligados_matriz,float64,396907,85.8552
qt_coligados_ativo,qt_coligados_ativo,float64,396907,85.8552
qt_coligados_baixada,qt_coligados_baixada,float64,396907,85.8552
qt_coligados_inapta,qt_coligados_inapta,float64,396907,85.8552
qt_coligados_nula,qt_coligados_nula,float64,396907,85.8552
idade_media_coligadas,idade_media_coligadas,float64,396907,85.8552
idade_maxima_coligadas,idade_maxima_coligadas,float64,396907,85.8552
qt_coligados_sa,qt_coligados_sa,float64,396907,85.8552
qt_coligados_me,qt_coligados_me,float64,396907,85.8552
grau_instrucao_macro_escolaridade_media,grau_instrucao_macro_escolaridade_media,float64,394501,85.3348
tx_crescimento_12meses,tx_crescimento_12meses,float64,388410,84.0172
tx_crescimento_24meses,tx_crescimento_24meses,float64,388284,83.9900
percent_func_genero_masc,percent_func_genero_masc,float64,386356,83.5729
percent_func_genero_fem,percent_func_genero_fem,float64,386356,83.5729
total,total,float64,386356,83.5729
media_meses_servicos,media_meses_servicos,float64,386037,83.5039
min_meses_servicos,min_meses_servicos,float64,386037,83.5039
max_meses_servicos,max_meses_servicos,float64,386037,83.5039
media_meses_servicos_all,media_meses_servicos_all,float64,358738,77.5989
max_meses_servicos_all,max_meses_servicos_all,float64,358738,77.5989
min_meses_servicos_all,min_meses_servicos_all,float64,358738,77.5989
qt_admitidos,qt_admitidos,float64,358724,77.5958
qt_admitidos_12meses,qt_admitidos_12meses,float64,358724,77.5958
qt_desligados_12meses,qt_desligados_12meses,float64,358724,77.5958
qt_desligados,qt_desligados,float64,358724,77.5958
qt_funcionarios,qt_funcionarios,float64,358724,77.5958
qt_funcionarios_12meses,qt_funcionarios_12meses,float64,358724,77.5958
qt_funcionarios_24meses,qt_funcionarios_24meses,float64,358724,77.5958
meses_ultima_contratacaco,meses_ultima_contratacaco,float64,358724,77.5958
tx_rotatividade,tx_rotatividade,float64,358724,77.5958
qt_ex_funcionarios,qt_ex_funcionarios,float64,347044,75.0693
qt_funcionarios_grupo,qt_funcionarios_grupo,float64,347035,75.0674
qt_socios_feminino,qt_socios_feminino,float64,317269,68.6287
qt_socios_masculino,qt_socios_masculino,float64,267183,57.7945
qt_socios_st_regular,qt_socios_st_regular,float64,154917,33.5102
idade_minima_socios,idade_minima_socios,float64,151602,32.7931
idade_media_socios,idade_media_socios,float64,151602,32.7931
idade_maxima_socios,idade_maxima_socios,float64,151602,32.7931
empsetorcensitariofaixarendapopulacao,empsetorcensitariofaixarendapopulacao,float64,143829,31.1118
qt_socios,qt_socios,float64,115091,24.8954
qt_socios_pj,qt_socios_pj,float64,115091,24.8954
qt_socios_pf,qt_socios_pf,float64,115091,24.8954
fl_optante_simples,fl_optante_simples,object,82713,17.8917
fl_optante_simei,fl_optante_simei,object,82713,17.8917
nm_micro_regiao,nm_micro_regiao,object,58698,12.6970
nm_meso_regiao,nm_meso_regiao,object,58698,12.6970
nu_meses_rescencia,nu_meses_rescencia,float64,45276,9.7937
vl_faturamento_estimado_grupo_aux,vl_faturamento_estimado_grupo_aux,float64,27513,5.9514
vl_faturamento_estimado_aux,vl_faturamento_estimado_aux,float64,27513,5.9514
de_faixa_faturamento_estimado_grupo,de_faixa_faturamento_estimado_grupo,object,27513,5.9514
de_faixa_faturamento_estimado,de_faixa_faturamento_estimado,object,27513,5.9514
de_saude_rescencia,de_saude_rescencia,object,14851,3.2124
de_saude_tributaria,de_saude_tributaria,object,14851,3.2124
de_nivel_atividade,de_nivel_atividade,object,11168,2.4158
sg_uf_matriz,sg_uf_matriz,object,1939,0.4194
fl_passivel_iss,fl_passivel_iss,object,1927,0.4168
setor,setor,object,1927,0.4168
nm_divisao,nm_divisao,object,1927,0.4168
fl_simples_irregular,fl_simples_irregular,object,1927,0.4168
nm_segmento,nm_segmento,object,1927,0.4168
vl_total_veiculos_pesados_grupo,vl_total_veiculos_pesados_grupo,float64,1927,0.4168
fl_veiculo,fl_veiculo,object,1927,0.4168
fl_antt,fl_antt,object,1927,0.4168
fl_spa,fl_spa,object,1927,0.4168
vl_total_veiculos_leves_grupo,vl_total_veiculos_leves_grupo,float64,1927,0.4168
dt_situacao,dt_situacao,object,6,0.0013
id,id,object,0,0.0000
fl_matriz,fl_matriz,bool,0,0.0000
fl_me,fl_me,bool,0,0.0000
de_natureza_juridica,de_natureza_juridica,object,0,0.0000
sg_uf,sg_uf,object,0,0.0000
natureza_juridica_macro,natureza_juridica_macro,object,0,0.0000
de_ramo,de_ramo,object,0,0.0000
idade_empresa_anos,idade_empresa_anos,float64,0,0.0000
idade_emp_cat,idade_emp_cat,object,0,0.0000
fl_sa,fl_sa,bool,0,0.0000
fl_rm,fl_rm,object,0,0.0000
fl_epp,fl_epp,bool,0,0.0000
fl_mei,fl_mei,bool,0,0.0000
fl_ltda,fl_ltda,bool,0,0.0000
fl_st_especial,fl_st_especial,bool,0,0.0000
fl_email,fl_email,bool,0,0.0000
fl_telefone,fl_telefone,bool,0,0.0000
qt_filiais,qt_filiais,int64,0,0.0000

In [11]:
market.describe()

,idade_empresa_anos,vl_total_tancagem,vl_total_veiculos_antt,vl_total_veiculos_leves,vl_total_veiculos_pesados,qt_art,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,vl_total_tancagem_grupo,vl_total_veiculos_antt_grupo,vl_potenc_cons_oleo_gas,nu_meses_rescencia,vl_frota,empsetorcensitariofaixarendapopulacao,qt_socios,qt_socios_pf,qt_socios_pj,idade_media_socios,idade_maxima_socios,idade_minima_socios,qt_socios_st_regular,qt_socios_st_suspensa,qt_socios_masculino,qt_socios_feminino,qt_socios_pep,qt_alteracao_socio_total,qt_alteracao_socio_90d,qt_alteracao_socio_180d,qt_alteracao_socio_365d,qt_socios_pj_ativos,qt_socios_pj_nulos,qt_socios_pj_baixados,qt_socios_pj_suspensos,qt_socios_pj_inaptos,vl_idade_media_socios_pj,vl_idade_maxima_socios_pj,vl_idade_minima_socios_pj,qt_coligados,qt_socios_coligados,qt_coligados_matriz,qt_coligados_ativo,qt_coligados_baixada,qt_coligados_inapta,qt_coligados_suspensa,qt_coligados_nula,idade_media_coligadas,idade_maxima_coligadas,idade_minima_coligadas,coligada_mais_nova_ativa,coligada_mais_antiga_ativa,idade_media_coligadas_ativas,coligada_mais_nova_baixada,coligada_mais_antiga_baixada,idade_media_coligadas_baixadas,qt_coligados_sa,qt_coligados_me,qt_coligados_mei,qt_coligados_ltda,qt_coligados_epp,qt_coligados_norte,qt_coligados_sul,qt_coligados_nordeste,qt_coligados_centro,qt_coligados_sudeste,qt_coligados_exterior,qt_ufs_coligados,qt_regioes_coligados,qt_ramos_coligados,qt_coligados_industria,qt_coligados_agropecuaria,qt_coligados_comercio,qt_coligados_serviço,qt_coligados_ccivil,qt_funcionarios_coligados,qt_funcionarios_coligados_gp,media_funcionarios_coligados_gp,max_funcionarios_coligados_gp,min_funcionarios_coligados_gp,vl_folha_coligados,media_vl_folha_coligados,max_vl_folha_coligados,min_vl_folha_coligados,vl_folha_coligados_gp,media_vl_folha_coligados_gp,max_vl_folha_coligados_gp,min_vl_folha_coligados_gp,faturamento_est_coligados,media_faturamento_est_coligados,max_faturamento_est_coligados,min_faturamento_est_coligados,faturamento_est_coligados_gp,media_faturamento_est_coligados_gp,max_faturamento_est_coligados_gp,min_faturamento_est_coligados_gp,total_filiais_coligados,media_filiais_coligados,max_filiais_coligados,min_filiais_coligados,qt_coligados_atividade_alto,qt_coligados_atividade_medio,qt_coligados_atividade_baixo,qt_coligados_atividade_mt_baixo,qt_coligados_atividade_inativo,qt_coligadas,sum_faturamento_estimado_coligadas,vl_faturamento_estimado_aux,vl_faturamento_estimado_grupo_aux,qt_ex_funcionarios,qt_funcionarios_grupo,percent_func_genero_masc,percent_func_genero_fem,idade_ate_18,idade_de_19_a_23,idade_de_24_a_28,idade_de_29_a_33,idade_de_34_a_38,idade_de_39_a_43,idade_de_44_a_48,idade_de_49_a_53,idade_de_54_a_58,idade_acima_de_58,grau_instrucao_macro_analfabeto,grau_instrucao_macro_escolaridade_fundamental,grau_instrucao_macro_escolaridade_media,grau_instrucao_macro_escolaridade_superior,grau_instrucao_macro_desconhecido,total,meses_ultima_contratacaco,qt_admitidos_12meses,qt_desligados_12meses,qt_desligados,qt_admitidos,media_meses_servicos_all,max_meses_servicos_all,min_meses_servicos_all,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
count,462298.000000,280.000000,176.000000,30684.000000,30684.000000,6590.000000,460371.000000,460371.000000,1760.000000,336.000000,3683.000000,417022.000000,2.419000e+04,318469.000000,347207.000000,347207.000000,347207.000000,310696.000000,310696.000000,310696.000000,307381.000000,3251.000000,195115.000000,145029.000000,6743.000000,0.0,0.0,0.0,0.0,4544.000000,4544.000000,4544.000000,4544.000000,4544.000000,4544.000000,4544.000000,4544.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.0,65391.000000,65391.000000,65391.000000,65147.000000,65147.000000,65147.000000,136.000000,136.000000,136.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,65391.000000,42303.000000,4.230300e+04,4.230300e+04,4.230300e+04,4.230300e+04,3.631400e+04,3.631400e+04,3.631400e+04,3.631400e+04,3.653700e+04,3.653700e+04,3.653700e+04,3.653700e+04,6.452300e+04,6.452300e+04,6.452300e+04,6.452300e+04,6.452300e+04,6.452300e+04,6.452300e+04,6.452300e+04,20400.000000,20400.000000,20400.000000,20400.000000,65391.0,65391.0,65391.0,65391.0,65391.0,50231.000000,4.954400e+04,4.347850e+05,4.347850e+05,115254.000000,1.152630e+05,75942.000000,75942.000000,2906.000000,25890.000000,38895.000000,40143.000000,36729.000000,30408.000000,24290.000000,19037.000000,13975.000000,11026.000000,1884.000000,24896.000000,67797.000000,22727.000000,0.0,75942.000000,103574.000000,103574.000000,103574.000000,103574.000000,103574.000000,103560.000000,103560.000000,103560.000000,76261.000000,76261.000000,76261.000000,103574.000000,103574.000000,103574.000000,73888.000000,74014.000000,103574.000000,462298.000000
mean,9.948677,32.014286,3.818182,2.244329,1.177813,5.769044,3.591801,48.699177,134.597159,15.934524,15.892131,25.007247,1.694226e+05,1308.005725,1.496326,1.476681,0.019645,42.816452,44.344131,41.355225,1.396082,1.048600,1.353925,1.107117,5.992437,NaN,NaN,NaN,NaN,1.453785,0.007262,0.013424,0.004842,0.021787,15.633042,17.667913,13.741865,5.744093,11.110336,5.715832,5.904528,0.003823,0.031931,0.000428,0.0,159.171741,227.625171,111.375456,111.385206,227.512334,159.137019,130.475490,137.824020,134.467034,0.719824,0.008518,0.027037,0.080225,0.001789,0.912251,0.136120,2.244376,0.239238,2.368430,0.015843,1.456179,1.225000,2.877323,0.529844,0.129743,1.169840,2.918230,1.205732,309.216344,1.940274e+03,3.649553e+02,1.538043e+03,1.552228e+02,4.528417e+07,5.863275e+06,2.258208e+07,2.261567e+06,1.144848e+08,1.580483e+07,6.708485e+07,5.446710e+06,8.843752e+08,2.314264e+07,4.006618e+08,8.986427e+05,1.006581e+09,3.045739e+07,4.731119e+08,1.381248e+06,60.301275,9.492187,34.664069,4.425539,0.0,0.0,0.0,0.0,0.0,3.175708,2.907904e+07,8.020911e+05,3.367205e+08,24.838418,1.109122e+04,55.699435,44.300577,2.197866,3.544998,4.247384,5.158932,5.634186,5.664661,5.480939,5.758155,6.115063,8.240522,2.248938,8.246465,11.496128,12.310336,NaN,16.706447,43.192861,2.101029,1.853148,27.698110,40.022679,41.965123,155.569411,16.200192,58.060498,96.661983,36.258851,12.324570,12.178529,14.343329,3.097607,-5.834288,9.510699,28.737044
std,9.615664,81.280168,6.797555,9.572536,6.589059,25.450950,72.600352,1206.696804,683.774506,29.708663,75.230681,9.679799,8.549075e+05,1161.889222,3.276626,3.258079,0.195166,12.626447,13.930385,12.514921,2.578793,0.234239,2.848980,0.840194,14.675005,NaN,NaN,NaN,NaN,0.840884,0.084919,0.124291,0.072522,0.177320,12.566365,14.650236,12.050708,24.271199,64.630753,24.225248,24.648572,0.118424,0.319076,0.020689,0.0,107.517745,165.354103,107.846354,108.050379,165.506417,107.734131,117.291388,115.312307,115.927221,4.843818,0.339126,0.172431,0.682837,0.051405,3.238254,1.293799,7.196462,2.092586,21.172714,0.165710,1.398458,0.641037,4.474460,4.903515,0.805483,5.493766,11.156578,17.818352,1493.910982,2.778422e+04,1.862561e+04,2.668126e+04,1.835361e+04,2.448707e+08,3.340987e+07,1.299719e+08,2.828363e+07,8.256886e+08,2.155833e+08,6.847121e+08,1.901343e+08,1.039876e+10,3.678229e+08,5.129334e+09,1.205634e+07,1.128959e+10,4.712580e+08,5.928130e+09,2.187560e+07,307.170442,72.316039,252.303510,64.860562,0.0,0.0,0.0,0.0,0.0,14.299979,7.876820e+08,3.099979e+07,7.114614e+09,192.458811,1.390161e+05,39.044407,39.044406,6.295785,20.727621,18.338771,30.416582,47.295036,53.753634,61.386164,86.572192,98.780740,133.597202,6.916321,76.710297,153.454754,163.623024,NaN,259.468814,123.945569,17.377796,15.590181,203.031275,377.411763,153.874093,637.850983,120.269302,142.951278,279.541243,123.411370,222.456579,222.584458,239.885359,163.581549,443.825819,27.918737,468.626094
min,0.016438,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.126000e+03,100.000000,1.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.600000,0.600000,0.600000,0.600000,0.600000,0.600000,0.800000,0.800000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.121280e+04,2.575800e+04,4.121280e+04,0.000000e+00,4.121280e+04,4.121280e+04,4.121280e+04,5.053000e+01,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000e+00,0.000000e+00,4.104703e+04,0.000000,0.000000e+00,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,1.933333,0.000000,0.000000,0.000000,1.000000,-102.466667,-102.466667,-102.466667,1.933333,1.933333,1.933333,0.000000,0.000000,0.000000,-100.000000,-100.000000,0.000000,0.000000
25%,2.756164,15.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,15.000000,1.000000,2.000000,22.000000,2.620500e+04,673.230000,1.000000,1.000000,0.000000,33.000000,34.000000,32.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,6.406571,7.041752,5.158795,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,80.758333,99.533333,30.333333,30.233333,99.050000,80.433333,60.766667,60.766667,60.766667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000e+00,1.500000e+00,2.000000e+00,0.000000e+00,2.060640e+05,1.751544e+05,1.854576e+05,6.181920e+04,2.472768e+05,1.854576e+05,1.854576e+05,6.181920e+04,2.100000e+05,2.100000e+05,2.100000e+05,2.100000e+05,2.100000e+05,2.100000e+05,2.100000e+05,2.100000e+05,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,1.000000,2.100000e+05,1.648512e+05,1.854576e+05,1.000000,1.000000e+00,16.670000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,9.300000,0.000000,0.000000,1.000000,2.000000,14.066667,25.366667,1.000000,25.203704,33.333333,6.966667,0.000000,0.000000,0.000000,0.000000,-44.444444,0.000000,0.000000
50%,6.704110,15.000000,2.000000,1.000000,0.000000,2.000000,0.000000,0.000000,15.000000,3.000000,4.000000,23.000000,5.169300e+04,946.680000,1.000000,1.000000,0.000000,42.000000,43.000000,40.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,11.739904,13.114305,10.193018,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.0,135.933333,193.666667,79.066667,78.800000,193.566667,135.803846,83.733333,99.433333,89.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,9.000000,1.000000e+01,6.000000e+00,8.000000e+00,1.000000e+00,8.036496e+05,4.842504e+05,6.181920e+05,1.854576e+05,9.272880e+05,5.392008e+05,7.006176e+05,1.854576e+05,7.418304e+05,3.158003e+05,4.121280e+05,2.100000e+05,8.654688e+05,4.200000e+05,5.769792e+05,2.100000e+05,3.000000,2.000000,2.000000,1.000000,0.0,0.0,0.0,0.0,0.0,1.000000,4.200000e+05,2.100000e+05,2.100000e+05,3.000000,2.000000e+00,60.000000,40.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,NaN,3.000000,30.300000,0.000000,0.000000,4.000000,6.000000,23.977778,53.666667,4.066667,43.533333,61.766667,23.200000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000
75%,14.465753,30.000000,4.000000,2.000000,1.000000,4.000000,0.000000,0.000000,66.250000,8.000000,10.000000,25.000000,1.165000e+05,1518.080000,2.000000,2.000000,0.000000,51.000000,54.000000,50.000000,1.000000,1.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN,NaN,2.000000,0.000000,0.000000,0.000000,0.000000,21.374401,23.835044,18.561259,4.000000,4.000000,3.000000,4.000000,0.000000,0.000000,0.000000,0.0,218.566667,315.066667,158.766667,159.066667,315.133333,218.958333,173.608333,188.208333,173.608333,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,2.000000,0.000000,49.000000,7.000000e+01,2.400000e+01,4.200000e+01,6.000000e+00,5.105235e+06,1.792757e+06,3.317630e+06,4.945536e+05,7.232846e+06,2.431555e+06,4.512802e+06,5.563728e+05,3.300960e+06,1.084200e+06,1.978214e+06,2.100000e+05,4.386392e+06,1.446384e+06,2.658226e+06,2.472768e+05,14.000000,4.400000,8.000000,2.000000,0.0,0.0,0.0,0.0,0.0,3.000000,1.577894e+06,2.100000e+05,2.100000e+05,11.000000,9.000000e+00,100.000000,83.330000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,6.000000,4.000000,NaN,8.000000,58.700000,1.000000,1.000000,13.000000,19.000000,40.033333,95.166667,13.200000,68.883333,96.266667,46.500000,5.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000
max,106.432877,1215.000000,50.000000,489.000000,363.000000,1017.000000,9782.000000,122090.000000,11922.000000,108.000000,3645.000000,66.000000,5.585830e+07,75093.840000,246.000000,246.000000,13.000000,127.000000,127.000000,127.000000,179.000000,6.000000,84.000000,140.000000,163.000000,NaN,NaN,NaN,NaN,12.000000,1.000000,2.000000,2.000000,6.000000,75.096509,101.144422,75.096509,844.000000,2059.000000,844.000000,843.000000,7.000000,25.000000,1.000000,0.0,910.333333,1358.166667,910.333333,910.333333,1358.166667,910.333333,634.200000,634.200000,634.200000,118.000000,42.000000,6.000000,29.000000,6.000000,221.000000,86.000000,288.000000,105.000000,728.000000,5.000000,25.000000,7.000000,86.000000,222.000000,30.000000,272.000000,229.000000,806.000000,32130.000000,2.668728e+06,2.668728e+06,2.668728e+06,2.668728e+06,5.370172e+09,1.205969e+09,3.321422e+09,1.205969e+09,2.461144e+10,2.461144e+10,2.461144e+10,2.461144e+10,3.390953e+11,5.576850e+10,1.673051e+11,8.735568e+08,3.728518e+11,7.425407e+10,2.227618e+11,2.660064e+09,7910.000000,6278.000000,7205.000000,6278.000000,0.0,0.0,0.0,0.0,0.0,761.000000,5.601337e+10,1.454662e+10,2.227618e+11,21555.000000,2.668728e+06,100.000000,100.000000,258.000000,2326.000000,1382.000000,3379.000000,6500.000000,6744.000000,6572.000000,9578.000000,9094.000000,9086.000000,196.000000,8161.000000,25071.000000,20616.000000,NaN,51540.000000,5099.066667,1957.000000,2230.000000,21565.000000,71748.000000,5099.066667,5099.066667,5099.066667,5099.066667,5099.066667,5099.066667,51547.000000,51547.000000,54205.000000,27800.000000,87300.000000,1400.000000,9647.000000

In [12]:
market.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 462298 entries, 0 to 462297
Columns: 181 entries, id to qt_filiais
dtypes: bool(9), float64(144), int64(1), object(27)
memory usage: 614.1+ MB

In [13]:
market.head()

,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,fl_me,fl_sa,fl_epp,fl_mei,fl_ltda,dt_situacao,fl_st_especial,fl_email,fl_telefone,fl_rm,nm_divisao,nm_segmento,fl_spa,fl_antt,fl_veiculo,vl_total_tancagem,vl_total_veiculos_antt,vl_total_veiculos_leves,vl_total_veiculos_pesados,fl_optante_simples,qt_art,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,vl_total_tancagem_grupo,vl_total_veiculos_antt_grupo,vl_potenc_cons_oleo_gas,fl_optante_simei,sg_uf_matriz,de_saude_tributaria,de_saude_rescencia,nu_meses_rescencia,de_nivel_atividade,de_indicador_telefone,fl_simples_irregular,vl_frota,empsetorcensitariofaixarendapopulacao,nm_meso_regiao,nm_micro_regiao,fl_passivel_iss,qt_socios,qt_socios_pf,qt_socios_pj,idade_media_socios,idade_maxima_socios,idade_minima_socios,qt_socios_st_regular,qt_socios_st_suspensa,qt_socios_masculino,qt_socios_feminino,qt_socios_pep,qt_alteracao_socio_total,qt_alteracao_socio_90d,qt_alteracao_socio_180d,qt_alteracao_socio_365d,qt_socios_pj_ativos,qt_socios_pj_nulos,qt_socios_pj_baixados,qt_socios_pj_suspensos,qt_socios_pj_inaptos,vl_idade_media_socios_pj,vl_idade_maxima_socios_pj,vl_idade_minima_socios_pj,qt_coligados,qt_socios_coligados,qt_coligados_matriz,qt_coligados_ativo,qt_coligados_baixada,qt_coligados_inapta,qt_coligados_suspensa,qt_coligados_nula,idade_media_coligadas,idade_maxima_coligadas,idade_minima_coligadas,coligada_mais_nova_ativa,coligada_mais_antiga_ativa,idade_media_coligadas_ativas,coligada_mais_nova_baixada,coligada_mais_antiga_baixada,idade_media_coligadas_baixadas,qt_coligados_sa,qt_coligados_me,qt_coligados_mei,qt_coligados_ltda,qt_coligados_epp,qt_coligados_norte,qt_coligados_sul,qt_coligados_nordeste,qt_coligados_centro,qt_coligados_sudeste,qt_coligados_exterior,qt_ufs_coligados,qt_regioes_coligados,qt_ramos_coligados,qt_coligados_industria,qt_coligados_agropecuaria,qt_coligados_comercio,qt_coligados_serviço,qt_coligados_ccivil,qt_funcionarios_coligados,qt_funcionarios_coligados_gp,media_funcionarios_coligados_gp,max_funcionarios_coligados_gp,min_funcionarios_coligados_gp,vl_folha_coligados,media_vl_folha_coligados,max_vl_folha_coligados,min_vl_folha_coligados,vl_folha_coligados_gp,media_vl_folha_coligados_gp,max_vl_folha_coligados_gp,min_vl_folha_coligados_gp,faturamento_est_coligados,media_faturamento_est_coligados,max_faturamento_est_coligados,min_faturamento_est_coligados,faturamento_est_coligados_gp,media_faturamento_est_coligados_gp,max_faturamento_est_coligados_gp,min_faturamento_est_coligados_gp,total_filiais_coligados,media_filiais_coligados,max_filiais_coligados,min_filiais_coligados,qt_coligados_atividade_alto,qt_coligados_atividade_medio,qt_coligados_atividade_baixo,qt_coligados_atividade_mt_baixo,qt_coligados_atividade_inativo,qt_coligadas,sum_faturamento_estimado_coligadas,de_faixa_faturamento_estimado,de_faixa_faturamento_estimado_grupo,vl_faturamento_estimado_aux,vl_faturamento_estimado_grupo_aux,qt_ex_funcionarios,qt_funcionarios_grupo,percent_func_genero_masc,percent_func_genero_fem,idade_ate_18,idade_de_19_a_23,idade_de_24_a_28,idade_de_29_a_33,idade_de_34_a_38,idade_de_39_a_43,idade_de_44_a_48,idade_de_49_a_53,idade_de_54_a_58,idade_acima_de_58,grau_instrucao_macro_analfabeto,grau_instrucao_macro_escolaridade_fundamental,grau_instrucao_macro_escolaridade_media,grau_instrucao_macro_escolaridade_superior,grau_instrucao_macro_desconhecido,total,meses_ultima_contratacaco,qt_admitidos_12meses,qt_desligados_12meses,qt_desligados,qt_admitidos,media_meses_servicos_all,max_meses_servicos_all,min_meses_servicos_all,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
0,a6984c3ae395090e3bee8ad63c3758b110de096d5d8195...,True,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRUÇÃO CIVIL,14.457534,10 a 15,False,False,False,False,False,2005-03-25,False,True,True,SIM,CONSTRUCAO DE EDIFICIOS,CONSTRUCAO,False,False,False,NaN,NaN,NaN,NaN,True,8.0,0.0,0.0,NaN,NaN,NaN,False,RN,VERDE,ACIMA DE 1 ANO,23.0,ALTA,BOA,False,NaN,NaN,LESTE POTIGUAR,NATAL,True,2.0,2.0,0.0,44.0,47.0,41.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,8.0,6.0,6.0,0.0,0.0,0.0,0.0,220.477778,536.366667,57.3,57.3,536.366667,220.477778,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,2.0,1.0,5.0,0.0,0.0,1.0,5.0,0.0,145.0,145.0,36.25,91.0,6.0,9375912.0,2343978.0,5275238.5,638798.4,9375912.0,2343978.0,5275238.5,638798.4,21809443.0,3.634907e+06,13188096.0,210000.0,22019443.0,3.669907e+06,13188096.0,210000.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,6.0,21809443.0,"DE R$ 1.500.000,01 A R$ 4.800.000,00","DE R$ 1.500.000,01 A R$ 4.800.000,00",3132172.8,3132172.8,119.0,26.0,100.0,0.0,NaN,1.0,4.0,6.0,5.0,3.0,4.0,2.0,NaN,1.0,NaN,1.0,25.0,NaN,NaN,26.0,19.166667,0.0,0.0,119.0,145.0,13.309195,93.266667,-0.933333,43.738462,93.266667,19.166667,26.0,26.0,27.0,0.0,-3.703704,0.0,0
1,6178f41ade1365e44bc2c46654c2c8c0eaae27dcb476c4...,True,EMPRESARIO INDIVIDUAL,PI,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVIÇO,1.463014,1 a 5,False,False,False,True,False,2017-05-12,False,True,True,SIM,ALIMENTACAO,ALOJAMENTO E ALIMENTACAO,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,PI,CINZA,ATE 1 ANO,9.0,BAIXA,NaN,False,NaN,468.93,CENTRO NORTE PIAUIENSE,TERESINA,True,1.0,1.0,0.0,27.0,27.0,27.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",210000.0,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02...,True,EMPRESARIO INDIVIDUAL,AM,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",SERVIÇO,7.093151,5 a 10,False,False,False,True,False,2011-09-26,False,False,True,SIM,TRANSPORTE TERRESTRE,TRANSPORTE ARMAZENAGEM E CORREIO,False,False,False,NaN,NaN,NaN,NaN,True,NaN,0.0,0.0,NaN,NaN,NaN,True,AM,AMARELO,ACIMA DE 1 ANO,26.0,MEDIA,NaN,False,NaN,713.50,CENTRO AMAZONENSE,MANAUS,True,1.0,1.0,0.0,32.0,32.0,32.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ATE R$ 81.000,00","ATE R$ 81.000,00",50000.0,50000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3348900fe63216a439d2e5238c79ddd46ede454df7b9d8...,True,EMPRESARIO INDIVIDUAL,AM,OUTROS,SERVICOS DIVERSOS,SERVIÇO,6.512329,5 a 10,False,False,False,False,False,2012-04-25,False,True,True,SIM,REPARACAO E MANUTENCAO DE EQUIPAMENTOS DE INFO...,OUTRAS ATIVIDADES DE SERVICOS,False,False,False,NaN,NaN,NaN,NaN,True,NaN,0.0,0.0,NaN,NaN,NaN,False,AM,AMARELO,ACIMA DE 1 ANO,26.0,MEDIA,NaN,False,NaN,475.73,CENTRO AMAZONENSE,MANAUS,True,1.0,1.0,0.0,36.0,36.0,36.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",210000.0,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1f9bcabc9d3173c1fe769899e4fac14b053037b953a1e4...,True,EMPRESARIO INDIVIDUAL,RN,OUTROS,"SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS",SERVIÇO,3.200000,1 a 5,False,False,False,False,False,2015-08-17,False,True,True,SIM,SERVICOS DE ARQUITETURA E ENGENHARIA TESTES E ...,ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS,False,False,False,NaN,NaN,NaN,NaN,True,NaN,0.0,0.0,NaN,NaN,NaN,False,RN,VERDE,ACIMA DE 1 ANO,27.0,ALTA,NaN,False,NaN,2874.04,LESTE POTIGUAR,NATAL,True,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",210000.0,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

### Dicionário dos dados

<ol>
    <li><b>fl_matriz:</b> valor bool, verdadeiro se o CNPJ for "matriz" </li>
    <li><b>de_natureza_juridica:</b> caráter, natureza jurídica da empresa</li>
    <li><b>sg_uf:</b> caractere, iniciais do nome do estado da empresa</li>
    <li><b>natureza_juridica_macro:</b> uma categoria macro legal para "natureza jurídica"</li>
    <li><b style="color:blue;">de_ramo:</b> descrição de uma categoria / ramificação de atividade de macro com base no código CNAE.</li>
    <li><b style="color:blue;">setor:</b> caráter, setor econômico da empresa (Indústria, Serviços, Agronegócios, Etc.)</li>
    <li><b>idade_empresa_anos:</b> valor numérico, idade da empresa.</li>
    <li><b>idade_emp_cat:</b> caractere, idade da empresa por faixas</li>
    <li><b>fl_me:</b> valor booleano, verdadeiro se a empresa tiver o termo 'ME' no final de seu nome legal.</li>
    <li><b>fl_sa:</b> valor booleano, verdadeiro se a empresa tiver o termo 'SA' no final de seu nome legal</li>
    <li><b>fl_epp:</b> valor booleano, verdadeiro se a empresa tiver o termo 'EPP' no final de seu nome legal.</li>
    <li><b>fl_mei:</b> valor booleano, verdadeiro se a empresa tiver o termo 'MEI' no final de seu nome legal.</li>
    <li><b>fl_ltda:</b> valor booleano, verdadeiro se a empresa tiver o termo 'LTDA' no final de seu nome legal.</li>
    <li><b>dt_situacao:</b> data em que a "de_situacao" foi registrada pelo IRS</li>
    <li><b>fl_st_especial:</b>  valor booleano, verdadeiro se dt_situacao_especial não for nulo. Se não for nulo, significa que alguns situação extraordinária é identificada pelo IRS</li>
    <li><b>fl_email:</b> valor booleano, true se o cnpj tiver um email registrado no banco de dados do IRF</li>
    <li><b>fl_telefone:</b> valor booleano, verdadeiro se a empresa tiver um número de telefone registrado no banco de dados do IRS</li>
    <li><b>fl_rm:</b> caractere, verdadeiro se o endereço da empresa estiver localizado em uma área metropolitana.</li>
    <li><b>nm_divisao:</b> caractere, descrição do nome da atividade econômica primária da empresa</li>
    <li><b style="color:blue;">nm_segmento:</b> caractere, descrição do nome do cluster de atividades econômicas principais da empresa</li>
    <li><b>fl_spa:</b> booleano, verdadeiro se a empresa tiver seu próprio posto de combustível</li>
    <li><b>fl_antt:</b> boolean, true se a empresa é certificada pela ANTT para fins de transporte</li>
    <li><b>fl_veiculo:</b> booleano, verdadeiro se a empresa possuir pelo menos um veículo</li>
    <li><b style="color:#EB8958">vl_total_tancagem:</b> capacidade numérica e total de armazenamento de combustível da empresa</li>
    <li><b style="color:#EB8958">vl_total_veiculos_antt:</b> número inteiro, número total de veículos da empresa</li>
    <li><b>vl_total_veiculos_leves:</b> número inteiro, número total de veículos leves da empresa</li>
    <li><b>vl_total_veiculos_pesados:</b> número inteiro, número total de veículos pesados ​​da empresa</li>
    <li><b>fl_optante_simples:</b> booleano, verdadeiro se a empresa for tributada de acordo com o regime SIMPLES</li>
    <li><b>qt_art:</b> número inteiro, número de construções (edifícios) autorizadas por um arquiteto</li>
    <li><b>vl_total_veiculos_pesados_grupo:</b> valor econômico numérico dos veículos pesados ​​do grupo econômico da empresa</li>
    <li><b>vl_total_veiculos_leves_grupo:</b> valor econômico numérico dos veículos leves do grupo econômico da empresa</li>
    <li><b style="color:#EB8958">vl_total_tancagem_grupo:</b> capacidade numérica total de armazenamento de combustível do grupo econômico da empresa</li>
    <li><b style="color:#EB8958">vl_total_veiculos_antt_grupo:</b> numérico, número total de veículos do grupo econômico da empresa que está registrado com certificação ANTT</li>
    <li><b>vl_potenc_cons_oleo_gas:</b> consumo numérico e potencial de petróleo e gás</li>
    <li><b>fl_optante_simei:</b> booleano, verdadeiro se a empresa for tributada como MEI</li>
    <li><b>sg_uf_matriz:</b> caractere, estado do local do escritório principal</li>
    <li><b>de_saude_tributaria:</b> caractere, indicador do status do imposto sobre saúde, Verde se todos os impostos estiverem OK, Vermelho se nenhum estiver OK</li>
    <li><b>de_saude_rescencia:</b> caractere, indica o tempo de atualização da entrada mais atrasada do indicador.</li>
    <li><b>nu_meses_rescencia:</b> caractere, número de meses desde a última atualização da entrada mais atrasada de saude_tributaria</li>
    <li><b>de_nivel_atividade:</b> caractere, probabilidade de estar em operação, ALTA com alta probabilidade, BAIXA, baixa probabilidade.</li>
    <li><b>de_indicador_telefone:</b> caractere, propabilidade para chegar à empresa usando os números de telefone fornecidos por
Neoway</li>
    <li><b>fl_simples_irregular:</b> boolean, true se a empresa é tributada pelo regime SIMPLES e possui uma CNAE impeditiva (atividades econômicas que não podem ser tributadas de acordo com o regime simples)
receita acima do limite do regime.</li>
    <li><b>vl_frota:</b> valor numérico agregado de todos os veículos da empresa</li>
    <li><b>empsetorcensitariofaixarendapopulacao:</b> renda média numérica de uma amostra de residentes em uma unidade censitária (menor área territorial de acordo com o IBGE)</li>
    <li><b>nm_meso_regiao:</b> caractere, nome da região meso em que a empresa está localizada.</li>
    <li><b>nm_micro_regiao:</b> caractere, nome da microrregião em que a empresa está localizada.</li>
    <li><b>fl_passivel_iss:</b> booleano, true se a empresa realizar alguma atividade tributável no ISS - Imposto sobre serviços.</li>
    <li><b>qt_socios:</b> valor inteiro, quantidade de parceiros / acionistas do cnpj</li>
    <li><b>qt_socios_pf:</b> valor inteiro, quantidade de parceiros / acionistas da cnpj que são pessoas
q</li>
    <li><b>qt_socios_pj:</b> valor inteiro, quantidade de parceiros / acionistas da cnpj que são empresas</li>
    <li><b>idade_media_socios:</b> valor numérico, idade média dos parceiros do cnpj (considera apenas os parceiros do cpf)</li>
    <li><b>idade_maxima_socios:</b> igual ao anterior, mas com métrica máxima</li>
    <li><b>idade_minima_socios:</b> igual ao anterior, mas com métrica mínima</li>
    <li><b>qt_socios_st_regular:</b> valor inteiro, quantidade de parceiros com situação regular no IRS - Receita Federal</li>
    <li><b>qt_socios_st_suspensa:</b> valor inteiro, quantidade de parceiros com situação suspensa no IRS - Receit Federal</li>
    <li><b>qt_socios_masculino:</b> valor inteiro, quantidade de parceiros masculinos</li>
    <li><b>qt_socios_feminino:</b> valor inteiro, quantidade de parceiras (mulheres)</li>
    <li><b>qt_socios_pep:</b> valor inteiro, quantidade de parceiros do cnpj expostos politicamente</li>
    <li><b style="color:red;">qt_alteracao_socio_total:</b> valor inteiro, quantidade de alterações no QSA</li>
    <li><b style="color:red;">qt_alteracao_socio_90d:</b>  valor inteiro, quantidade de alterações no QSA nos últimos 90 dias</li>
    <li><b style="color:red;">qt_alteracao_socio_180d:</b>  valor inteiro, quantidade de alterações no QSA nos últimos 180 dias</li>
    <li><b style="color:red;">qt_alteracao_socio_365d:</b>  valor inteiro, quantidade de alterações no QSA nos últimos 365 dias</li>
    <li><b>qt_socios_pj_ativos:</b> valor inteiro, quantidade de parceiros PJ que são ATIVA no RF.</li>
    <li><b>qt_socios_pj_nulos:</b> valor inteiro, quantidade de parceiros PJ que são NULA no RF</li>
    <li><b>qt_socios_pj_baixados:</b> valor inteiro, quantidade de parceiros PJ que são BAIXADA no RF.</li>
    <li><b>qt_socios_pj_suspensos:</b> valor inteiro, quantidade de parceiros PJ que são SUSPENSA no RF.</li>
    <li><b>qt_socios_pj_inaptos:</b> valor inteiro, quantidade de parceiros PJ que são INAPTA no RF.</li>
    <li><b>vl_idade_media_socios_pj:</b> valor flutuante, idade média dos parceiros PJ.</li>
    <li><b>vl_idade_maxima_socios_pj:</b> valor flutuante, idade máxima dos parceiros PJ.</li>
    <li><b>vl_idade_minima_socios_pj:</b> valor flutuante, idade mínima dos parceiros PJ.</li>
    <li><b>qt_coligados:</b> valor inteiro, quantidade de empresas conectadas</li>
    <li><b>qt_socios_coligados:</b> valor inteiro, soma de parceiros de empresas conectadas</li>
    <li><b>qt_coligados_matriz:</b> valor inteiro, quantidade de empresas conectadas que são uma empresa matricial</li>
    <li><b>qt_coligados_ativo:</b> valor inteiro, quantidade de empresas conectadas consideradas ativas de acordo com o IRS - receita federal</li>
    <li><b>qt_coligados_baixada:</b> valor inteiro, quantidade de empresas conectadas consideradas fechadas de acordo com o IRS</li>
    <li><b>qt_coligados_inapta:</b> valor inteiro, quantidade de empresas conectadas consideradas inaptas / impróprias de acordo com o IRS</li>
    <li><b>qt_coligados_suspensa:</b> valor inteiro, quantidade de empresas conectadas que são consideradas suspensas de acordo com o IRS</li>
    <li><b>qt_coligados_nula:</b> valor inteiro, quantidade de empresas conectadas que são consideradas empresas nulos de acordo com o IRS</li>
    <li><b>idade_media_coligadas:</b> float, idade média (meses) de empresas conectadas</li>
    <li><b>idade_maxima_coligadas:</b> float, idade máxima (meses) de empresas conectadas</li>
    <li><b>idade_minima_coligadas:</b> float, idade mínima (meses) das empresas conectadas</li>
    <li><b>coligada_mais_nova_ativa:</b> flutuador, idade (meses) da colagem mais jovem que está ativa</li>
    <li><b>coligada_mais_antiga_ativa:</b> flutuador, idade (meses) da colagem mais antiga que está ativa</li>
    <li><b>idade_media_coligadas_ativas:</b> float, idade média (meses) de empresas conectadas ativas</li>
    <li><b style="color:#EB8958">coligada_mais_nova_baixada:</b> flutuador, idade (meses) da sua colagem fechada</li>
    <li><b style="color:#EB8958;">coligada_mais_antiga_baixada:</b> flutuador, idade (meses) da colagem fechada mais antiga</li>
    <li><b style="color:#EB8958;">idade_media_coligadas_baixadas:</b> flutuador, média (meses) de colagem fechada</li>
    <li><b>qt_coligados_sa:</b> valor inteiro, quantidade de empresas conectadas que possuem o termo SA no final do nome da empresa</li>
    <li><b>qt_coligados_me:</b> valor inteiro, quantidade de empresas conectadas que possuem o termo ME no final do nome da empresa</li>
    <li><b>qt_coligados_mei:</b> valor inteiro, quantidade de empresas conectadas que possuem o termo MEI no final do nome da empresa</li>
    <li><b>qt_coligados_ltda:</b> valor inteiro, quantidade de empresas conectadas que possuem o termo LTDA no final do nome da empresa</li>
    <li><b>qt_coligados_epp:</b> valor inteiro, quantidade de empresas conectadas que possuem o termo EPP no final do nome da empresa</li>
    <li><b>qt_coligados_norte:</b> valor inteiro, quantidade de empresas conectadas localizadas na região norte do país</li>
    <li><b>qt_coligados_sul:</b> valor inteiro, quantidade de empresas conectadas localizadas na região sul do país</li>
    <li><b>qt_coligados_nordeste:</b> valor inteiro, quantidade de empresas conectadas localizadas na região nordeste do país</li>
    <li><b>qt_coligados_centro:</b> valor inteiro, quantidade de empresas conectadas localizadas na região centro-oeste (centro-oeste) do país</li>
    <li><b>qt_coligados_sudeste:</b> valor inteiro, quantidade de empresas conectadas localizadas no sudeste do país</li>
    <li><b>qt_coligados_exterior:</b> valor inteiro, quantidade de empresas conectadas localizadas no exterior no país</li>
    <li><b>qt_ufs_coligados:</b> valor inteiro, quantidade de estados distintos em que as empresas conectadas estão localizadas</li>
    <li><b>qt_regioes_coligados:</b> valor inteiro, quantidade de ufs distintos em que as empresas conectadas estão localizadas</li>
    <li><b>qt_ramos_coligados:</b> valor inteiro, quantidade de ramos econômicos distintos de empresas conectadas</li>
    <li><b>qt_coligados_industria:</b> valor inteiro, quantidade de empresas conectadas do setor industrial</li>
    <li><b>qt_coligados_agropecuaria:</b> valor inteiro, quantidade de empresas conectadas do setor de agronegócio</li>
    <li><b>qt_coligados_comercio:</b> valor inteiro, quantidade de empresas conectadas</li>
    <li><b>qt_coligados_serviço:</b> valor inteiro, quantidade de empresas conectadas do setor de serviços</li>
    <li><b>qt_coligados_ccivil:</b> valor inteiro, quantidade de empresas conectadas do setor de construção</li>
    <li><b>qt_funcionarios_coligados:</b> valor inteiro, quantidade de funcionários das empresas conectadas</li>
    <li><b>qt_funcionarios_coligados_gp:</b> valor inteiro, quantidade de funcionários de empresas conectadas e de suas subsidiárias</li>
    <li><b>media_funcionarios_coligados_gp:</b> valor numérico, média de funcionários das empresas conectadas e de suas subsidiárias</li>
    <li><b>max_funcionarios_coligados_gp:</b> valor numérico, número máximo de funcionários de empresas conectadas e suas subsidiárias</li>
    <li><b>min_funcionarios_coligados_gp:</b> valor numérico, número mínimo de funcionários de empresas conectadas e suas subsidiárias</li>
    <li><b>vl_folha_coligados:</b> valor numérico, soma do valor da folha de pagamento de empresas conectadas</li>
    <li><b>media_vl_folha_coligados:</b> valor numérico, média do valor da folha de pagamento de empresas conectadas</li>
    <li><b>max_vl_folha_coligados:</b> valor numérico, máximo do valor da folha de pagamento de empresas conectadas</li>
    <li><b>min_vl_folha_coligados:</b> valor numérico, mínimo do valor da folha de pagamento de empresas conectadas</li>
    <li><b>vl_folha_coligados_gp:</b> valor numérico, soma do valor da folha de pagamento das empresas conectadas e de suas subsidiárias</li>
    <li><b>media_vl_folha_coligados_gp:</b> valor numérico, média do valor da folha de pagamento das empresas conectadas e de suas subsidiárias</li>
    <li><b>max_vl_folha_coligados_gp:</b> valor numérico, máximo do valor da folha de pagamento das empresas conectadas e de suas subsidiárias</li>
    <li><b>min_vl_folha_coligados_gp:</b> valor numérico, mínimo do valor da folha de pagamento das empresas conectadas e de suas subsidiárias</li>
    <li><b>faturamento_est_coligados:</b> valor numérico, soma da receita estimada de empresas conectadas</li>
    <li><b>media_faturamento_est_coligados:</b> valor numérico, média da receita estimada de empresas conectadas</li>
    <li><b>max_faturamento_est_coligados:</b> valor numérico, máximo da receita estimada de empresas conectadas</li>
    <li><b>min_faturamento_est_coligados:</b> valor numérico, mínimo da receita estimada de empresas conectadas</li>
    <li><b>faturamento_est_coligados_gp:</b> valor numérico, soma da receita estimada de empresas conectadas e de suas subsidiárias</li>
    <li><b>media_faturamento_est_coligados_gp:</b> valor numérico, média da receita estimada de empresas conectadas e de suas subsidiárias</li>
    <li><b>max_faturamento_est_coligados_gp:</b> valor numérico, valor máximo da receita estimada das empresas conectadas e de suas subsidiárias</li>
    <li><b>min_faturamento_est_coligados_gp:</b> valor numérico, valor mínimo da receita estimada das empresas conectadas e de suas subsidiárias</li>
    <li><b>total_filiais_coligados:</b> valor inteiro, quantidade de subsidiárias de empresas conectadas</li>
    <li><b>media_filiais_coligados:</b> valor numérico, média de subsidiárias de empresas conectadas</li>
    <li><b>max_filiais_coligados:</b> valor numérico, número máximo de subsidiárias de empresas conectadas</li>
    <li><b>min_filiais_coligados:</b> valor numérico, número mínimo de subsidiárias de empresas conectadas</li>
    <li><b>qt_coligados_atividade_alto:</b> valor inteiro, quantidade de empresas conectadas com classificador de nível de atividade estimado igual a 'ALTO'</li>
    <li><b>qt_coligados_atividade_medio:</b> valor inteiro, quantidade de empresas conectadas com classificador de nível de atividade estimado igual a 'Medio'</li>
    <li><b>qt_coligados_atividade_baixo:</b> valor inteiro, quantidade de empresas conectadas com classificador de nível de atividade estimado igual a 'Baixo'</li>
    <li><b>qt_coligados_atividade_mt_baixo:</b> valor inteiro, quantidade de empresas conectadas com classificador de nível de atividade estimado igual a 'Muito Baixo'</li>
    <li><b>qt_coligados_atividade_inativo:</b> valor inteiro, quantidade de empresas conectadas com classificador de nível de atividade estimado igual a 'INATIVO'</li>
    <li><b>qt_coligadas:</b> número de empresas vinculadas, ou seja, empresas em que um dos principais proprietários (CJNPJ referenciado) tem participação.</li>
    <li><b>sum_faturamento_estimado_coligadas:</b> a soma das estimativas de allcoligadas</li>
    <li><b>de_faixa_faturamento_estimado:</b> valor do caractere, classe da receita estimada da empresa</li>
    <li><b>de_faixa_faturamento_estimado_grupo:</b> valor do caractere, classe da soma da receita estimada da empresa matriz e filiais</li>
    <li><b>vl_faturamento_estimado_aux:</b> valor numérico, valor da receita estimada</li>
    <li><b>vl_faturamento_estimado_grupo_aux:</b>  valor numérico, soma da receita estimada para a empresa matriz e as filiais</li>
    <li><b>qt_ex_funcionarios:</b> valor inteiro, número de funcionários que deixaram a empresa.</li>
    <li><b>qt_funcionarios_grupo:</b> valor inteiro, quantidade de funcionários ativos considerando as filiais e a matriz.</li>
    <li><b>percent_func_genero_masc:</b> valor numérico, participação de funcionários do sexo masculino na empresa</li>
    <li><b>percent_func_genero_fem:</b> valor numérico, participação de funcionárias na empresa</li>
    <li><b>idade_ate_18:</b> valor inteiro, quantidade de funcionários com menos de 18 anos de idade.</li>
    <li><b>idade_de_19_a_23:</b> valor inteiro, quantidade de funcionários com idade entre 19 e 23 anos</li>
    <li><b>idade_de_24_a_28:</b> valor inteiro, quantidade de funcionários com idade entre 24 e 28 anos.</li>
    <li><b>idade_de_29_a_33:</b> valor inteiro, quantidade de funcionários com idade entre 29 e 33 anos.</li>
    <li><b>idade_de_34_a_38:</b> valor inteiro, quantidade de funcionários com idade entre 34 e 38 anos.</li>
    <li><b>idade_de_39_a_43:</b> valor inteiro, quantidade de funcionários com idade entre 39 e 43 anos.</li>
    <li><b>idade_de_44_a_48:</b> valor inteiro, quantidade de funcionários com idade entre 44 e 48 anos.</li>
    <li><b>idade_de_49_a_53:</b> valor inteiro, quantidade de funcionários com idade entre 49 e 53 anos.</li>
    <li><b>idade_de_54_a_58:</b> valor inteiro, quantidade de funcionários com idade entre 54 e 58 anos</li>
    <li><b>idade_acima_de_58:</b> valor inteiro, quantidade de funcionários com idade acima</li>
    <li><b>grau_instrucao_macro_analfabeto:</b> valor inteiro, quantidade de funcionários em posições sem necessidade de escolaridade.</li>
    <li><b>grau_instrucao_macro_escolaridade_fundamental:</b> valor inteiro, quantidade de empregados em posições com o nível fundamental exigido (completo e incompleto)</li>
    <li><b>grau_instrucao_macro_escolaridade_media:</b> valor inteiro, soma de grau_instrucao_medio_incompl e grau_instrucao_medio_compl</li>
    <li><b>grau_instrucao_macro_escolaridade_superior:</b> valor inteiro, soma de grau_instrucao_sup_incompl, grau_instrucao_sup_compl, grau_instrucao_mestrado e grau_instrucao_doutorado</li>
    <li><b style="color:red;">grau_instrucao_macro_desconhecido:</b> valor inteiro, o mesmo que grau_instrucao_desconhecido</li>
    <li><b>total:</b> valor inteiro, número real de funcionários da empresa</li>
    <li><b>meses_ultima_contratacaco:</b>  numérico, meses desde a última contratação.</li>
    <li><b>qt_admitidos_12meses:</b> número inteiro, quantidade de funcionários contratados nos últimos 12 meses</li>
    <li><b>qt_desligados_12meses:</b> número inteiro, quantidade de funcionários demitidos nos últimos 12 meses</li>
    <li><b>qt_desligados:</b> número inteiro, quantidade de funcionários demitidos pela empresa</li>
    <li><b>qt_admitidos:</b> número inteiro, quantidade de funcionários contratados pela empresa</li>
    <li><b>media_meses_servicos_all:</b> numérico, número médio de meses trabalhados por todos os funcionários da empresa (ativos e demitidos)</li>
    <li><b>max_meses_servicos_all:</b> numérico, número máximo de meses trabalhados por todos os funcionários da empresa (ativos e demitidos)</li>
    <li><b>min_meses_servicos_all:</b> numérico, número mínimo de meses trabalhados por todos os funcionários da empresa (ativos e demitidos)</li>
    <li><b>media_meses_servicos:</b> numérico, número médio de meses trabalhados pelos funcionários ativos da empresa</li>
    <li><b>max_meses_servicos:</b> numérico, número máximo de meses trabalhados pelos funcionários ativos da empresa</li>
    <li><b>min_meses_servicos:</b> numérico, número mínimo de meses trabalhados pelos funcionários ativos da empresa</li>
    <li><b>qt_funcionarios:</b> número inteiro, quantidade de empregados reais</li>
    <li><b>qt_funcionarios_12meses:</b> número inteiro, quantidade de funcionários ativos 12 meses antes</li>
    <li><b>qt_funcionarios_24meses:</b> número inteiro, quantidade de funcionários ativos 24 meses antes</li>
    <li><b>tx_crescimento_12meses:</b> número inteiro, crescimento de funcionários em relação ao número de funcionários 12 meses antes</li>
    <li><b>tx_crescimento_24meses:</b> número inteiro, crescimento de funcionários em relação ao número de funcionários 24 meses antes</li>
    <li><b>tx_rotatividade:</b> número inteiro, mede a estabilidade geral dos funcionários considerando a contratação e demissões e o número real de funcionários.</li>
    <li><b>qt_filiais:</b> auto-explicativo.</li>
</ol>

### Verificando colunas com número grande de NaN

In [14]:
market_clean = filter_columns(market)

In [15]:
exploracao(market_clean)

,coluna,tipos,qtd_null,percent_null
fl_optante_simples,fl_optante_simples,object,82713,17.8917
fl_optante_simei,fl_optante_simei,object,82713,17.8917
nm_micro_regiao,nm_micro_regiao,object,58698,12.6970
nm_meso_regiao,nm_meso_regiao,object,58698,12.6970
nu_meses_rescencia,nu_meses_rescencia,float64,45276,9.7937
de_faixa_faturamento_estimado_grupo,de_faixa_faturamento_estimado_grupo,object,27513,5.9514
de_faixa_faturamento_estimado,de_faixa_faturamento_estimado,object,27513,5.9514
vl_faturamento_estimado_aux,vl_faturamento_estimado_aux,float64,27513,5.9514
vl_faturamento_estimado_grupo_aux,vl_faturamento_estimado_grupo_aux,float64,27513,5.9514
de_saude_rescencia,de_saude_rescencia,object,14851,3.2124
de_saude_tributaria,de_saude_tributaria,object,14851,3.2124
de_nivel_atividade,de_nivel_atividade,object,11168,2.4158
sg_uf_matriz,sg_uf_matriz,object,1939,0.4194
vl_total_veiculos_pesados_grupo,vl_total_veiculos_pesados_grupo,float64,1927,0.4168
vl_total_veiculos_leves_grupo,vl_total_veiculos_leves_grupo,float64,1927,0.4168
fl_antt,fl_antt,object,1927,0.4168
fl_veiculo,fl_veiculo,object,1927,0.4168
fl_spa,fl_spa,object,1927,0.4168
nm_segmento,nm_segmento,object,1927,0.4168
nm_divisao,nm_divisao,object,1927,0.4168
setor,setor,object,1927,0.4168
fl_passivel_iss,fl_passivel_iss,object,1927,0.4168
fl_simples_irregular,fl_simples_irregular,object,1927,0.4168
dt_situacao,dt_situacao,object,6,0.0013
fl_sa,fl_sa,bool,0,0.0000
fl_telefone,fl_telefone,bool,0,0.0000
fl_email,fl_email,bool,0,0.0000
fl_st_especial,fl_st_especial,bool,0,0.0000
fl_ltda,fl_ltda,bool,0,0.0000
fl_mei,fl_mei,bool,0,0.0000
fl_epp,fl_epp,bool,0,0.0000
fl_rm,fl_rm,object,0,0.0000
de_ramo,de_ramo,object,0,0.0000
idade_emp_cat,idade_emp_cat,object,0,0.0000
idade_empresa_anos,idade_empresa_anos,float64,0,0.0000
natureza_juridica_macro,natureza_juridica_macro,object,0,0.0000
sg_uf,sg_uf,object,0,0.0000
de_natureza_juridica,de_natureza_juridica,object,0,0.0000
fl_me,fl_me,bool,0,0.0000
fl_matriz,fl_matriz,bool,0,0.0000
id,id,object,0,0.0000
qt_filiais,qt_filiais,int64,0,0.0000

### Verificando os segmentos existentes

In [16]:
market.nm_segmento.value_counts()

COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS           211224
OUTRAS ATIVIDADES DE SERVICOS                                         59561
INDUSTRIAS DE TRANSFORMACAO                                           31968
ALOJAMENTO E ALIMENTACAO                                              30180
CONSTRUCAO                                                            25363
ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEMENTARES                  21326
ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS                       17371
TRANSPORTE ARMAZENAGEM E CORREIO                                      15485
EDUCACAO                                                              11311
SAUDE HUMANA E SERVICOS SOCIAIS                                       10139
ARTES CULTURA ESPORTE E RECREACAO                                      5503
INFORMACAO E COMUNICACAO                                               5475
ATIVIDADES FINANCEIRAS DE SEGUROS E SERVICOS RELACIONADOS              3287
AGRICULTURA PECUARIA PRODUCAO FLORESTAL PESCA E AQUICULTURA            3247
ADMINISTRACAO PUBLICA DEFESA E SEGURIDADE SOCIAL                       2754
ATIVIDADES IMOBILIARIAS                                                2670
AGUA ESGOTO ATIVIDADES DE GESTAO DE RESIDUOS E DESCONTAMINACAO         1238
INDUSTRIAS EXTRATIVAS                                                   896
SERVICOS DOMESTICOS                                                     757
ELETRICIDADE E GAS                                                      607
ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOES EXTRATERRITORIAIS         9
Name: nm_segmento, dtype: int64

### Verificando os setores existentes

In [17]:
market.setor.value_counts()

COMERCIO            211224
SERVIÇO             189644
INDUSTRIA            30893
CONSTRUÇÃO CIVIL     25363
AGROPECUARIA          3247
Name: setor, dtype: int64

### Verificando os ramos existentes

In [18]:
market.de_ramo.value_counts()

COMERCIO VAREJISTA                                   172404
SERVICOS DIVERSOS                                     60318
SERVICOS DE ALOJAMENTO/ALIMENTACAO                    30180
INDUSTRIA DA CONSTRUCAO                               25363
COMERCIO E REPARACAO DE VEICULOS                      22356
SERVICOS ADMINISTRATIVOS                              21326
BENS DE CONSUMO                                       21227
SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS        17371
COMERCIO POR ATACADO                                  16464
TRANSPORTE, ARMAZENAGEM E CORREIO                     15485
SERVICOS DE EDUCACAO                                  11311
SERVICOS DE SAUDE                                      9788
CULTURA, ESPORTE E RECREACAO                           5503
SIDERURGICA-METALURGIA                                 3700
TELECOM                                                3626
PRODUTOS DE AGROPECUARIA                               3247
QUIMICA-PETROQUIMICA                                   3131
ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL      2754
ATIVIDADES IMOBILIARIAS                                2670
PAPEL E CELULOSE                                       2179
OUTROS                                                 1927
INDUSTRIA DIGITAL                                      1849
SEGUROS, PLANOS DE PREVIDENCIA E PLANOS DE SAUDE       1770
SERVICOS FINANCEIROS                                   1517
SERVICOS DE SANEAMENTO BASICO                          1238
TEXTEIS                                                1048
INDUSTRIAS EXTRATIVAS                                   896
ELETRICIDADE E GAS                                      607
INDUSTRIA AUTOMOTIVA                                    410
SERVICOS SOCIAIS                                        351
ELETROELETRONICOS                                       251
FARMACEUTICA                                             22
ORGANISMOS INTERNACIONAIS                                 9
Name: de_ramo, dtype: int64

## EDA da empresa 1

In [19]:
empresa_1_ids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      555 non-null    object
dtypes: object(1)
memory usage: 4.5+ KB

In [20]:
empresa_1_ids.head()

                                                  id
0  dabe79bec87c88ae04e869bf6bd321ee5e1893cecf6625...
1  32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...
2  a95d6f30bba445bd3d6b0c5b36f865b38ec01d17336090...
3  6cb309685cea0b6d2988818792ec2e6fcb2bd02e0afa9e...
4  f72aa7fa6787b0a5a1c88885b6120850df8ee0f71adc25...

### Criando df com todas as info dos clientes da empresa 1

In [21]:
id_empresa1_market = market.id.isin(empresa_1_ids.id)

In [22]:
df_empresa1 = market[id_empresa1_market]

### Verificando segmentos existentes na empresa 1

In [23]:
df_empresa1.nm_segmento.value_counts()

COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS    496
INDUSTRIAS DE TRANSFORMACAO                                    59
Name: nm_segmento, dtype: int64

### Verificando setores existentes na empresa 1

In [24]:
df_empresa1.setor.value_counts()

COMERCIO     496
INDUSTRIA     52
SERVIÇO        7
Name: setor, dtype: int64

### Verificando os ramos existentes na empresa 1

In [25]:
df_empresa1.de_ramo.value_counts()

COMERCIO VAREJISTA    496
BENS DE CONSUMO        59
Name: de_ramo, dtype: int64

## EDA da empresa 2

In [26]:
empresa_2_ids.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566 entries, 0 to 565
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      566 non-null    object
dtypes: object(1)
memory usage: 8.8+ KB

In [27]:
empresa_2_ids.head()

                                                  id
0  09e95c1a84049001d086470a8f320a19b076f955a89122...
1  dc9d155f5bcd3172031e2ec9431786e8871ff4b0ff4728...
2  16843c9ffb920170477118933798510d8d5f00f5c56c12...
3  ff045934d90aab184dd15e66daf3b3c97193bda5449298...
4  a0ce528caab2c62497a548d0ebd9e935143ef81ed7dbf0...

### Criando df com todas as info dos clientes da empresa 2

In [28]:
id_empresa2_market = market.id.isin(empresa_2_ids.id)

In [29]:
df_empresa2 = market[id_empresa2_market]

### Verificando segmentos existentes na empresa 2

In [30]:
df_empresa2.nm_segmento.value_counts()

ADMINISTRACAO PUBLICA DEFESA E SEGURIDADE SOCIAL                  163
COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS        107
INDUSTRIAS DE TRANSFORMACAO                                        64
CONSTRUCAO                                                         46
ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEMENTARES               42
EDUCACAO                                                           33
TRANSPORTE ARMAZENAGEM E CORREIO                                   25
SAUDE HUMANA E SERVICOS SOCIAIS                                    25
OUTRAS ATIVIDADES DE SERVICOS                                      12
ALOJAMENTO E ALIMENTACAO                                           11
AGRICULTURA PECUARIA PRODUCAO FLORESTAL PESCA E AQUICULTURA         8
ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS                     6
AGUA ESGOTO ATIVIDADES DE GESTAO DE RESIDUOS E DESCONTAMINACAO      6
INFORMACAO E COMUNICACAO                                            6
ATIVIDADES FINANCEIRAS DE SEGUROS E SERVICOS RELACIONADOS           4
ELETRICIDADE E GAS                                                  3
ATIVIDADES IMOBILIARIAS                                             2
INDUSTRIAS EXTRATIVAS                                               2
ARTES CULTURA ESPORTE E RECREACAO                                   1
Name: nm_segmento, dtype: int64

### Verificando setores existentes na empresa 2

In [31]:
df_empresa2.setor.value_counts()

SERVIÇO             336
COMERCIO            107
INDUSTRIA            69
CONSTRUÇÃO CIVIL     46
AGROPECUARIA          8
Name: setor, dtype: int64

### Verificando os ramos existentes na empresa 2

In [32]:
df_empresa2.de_ramo.value_counts()

ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL    163
INDUSTRIA DA CONSTRUCAO                               46
COMERCIO VAREJISTA                                    46
SERVICOS ADMINISTRATIVOS                              42
COMERCIO POR ATACADO                                  40
SERVICOS DE EDUCACAO                                  33
QUIMICA-PETROQUIMICA                                  27
SERVICOS DE SAUDE                                     25
TRANSPORTE, ARMAZENAGEM E CORREIO                     25
COMERCIO E REPARACAO DE VEICULOS                      21
BENS DE CONSUMO                                       19
SERVICOS DIVERSOS                                     12
SERVICOS DE ALOJAMENTO/ALIMENTACAO                    11
PRODUTOS DE AGROPECUARIA                               8
SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS         6
SIDERURGICA-METALURGIA                                 6
SERVICOS DE SANEAMENTO BASICO                          6
ELETROELETRONICOS                                      4
TELECOM                                                4
PAPEL E CELULOSE                                       4
INDUSTRIA AUTOMOTIVA                                   3
ELETRICIDADE E GAS                                     3
INDUSTRIA DIGITAL                                      2
ATIVIDADES IMOBILIARIAS                                2
INDUSTRIAS EXTRATIVAS                                  2
SERVICOS FINANCEIROS                                   2
SEGUROS, PLANOS DE PREVIDENCIA E PLANOS DE SAUDE       2
CULTURA, ESPORTE E RECREACAO                           1
TEXTEIS                                                1
Name: de_ramo, dtype: int64

## EDA da empresa 3

In [33]:
empresa_3_ids.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 265 entries, 0 to 264
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      265 non-null    object
dtypes: object(1)
memory usage: 4.1+ KB

In [34]:
empresa_3_ids.head()

                                                  id
0  bb61c09449a1c1f8b78955d8b7a7f73599e78358993fe2...
1  16843c9ffb920170477118933798510d8d5f00f5c56c12...
2  1b8d092daff12bed8b3c2ab93bf5df2921865a68aca185...
3  3aafa3a1f12f483740a52956af100223333d0e3c79bf2c...
4  c60431fbca90067f105570e1e8a684bcd7048205bbf6c4...

### Criando df com todas as info dos clientes da empresa 3

In [35]:
id_empresa3_market = market.id.isin(empresa_3_ids.id)

In [36]:
df_empresa3 = market[id_empresa3_market]

### Verificando segmentos existentes na empresa 3

In [37]:
df_empresa3.nm_segmento.value_counts()

ADMINISTRACAO PUBLICA DEFESA E SEGURIDADE SOCIAL                  150
ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEMENTARES               35
EDUCACAO                                                           22
TRANSPORTE ARMAZENAGEM E CORREIO                                   14
SAUDE HUMANA E SERVICOS SOCIAIS                                    14
ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS                     5
AGUA ESGOTO ATIVIDADES DE GESTAO DE RESIDUOS E DESCONTAMINACAO      5
ATIVIDADES FINANCEIRAS DE SEGUROS E SERVICOS RELACIONADOS           5
ALOJAMENTO E ALIMENTACAO                                            5
OUTRAS ATIVIDADES DE SERVICOS                                       4
INFORMACAO E COMUNICACAO                                            4
ARTES CULTURA ESPORTE E RECREACAO                                   1
ATIVIDADES IMOBILIARIAS                                             1
Name: nm_segmento, dtype: int64

### Verificando setor existentes na empresa 3

In [38]:
df_empresa3.setor.value_counts()

SERVIÇO    265
Name: setor, dtype: int64

### Verificando os ramos existentes na empresa 3

In [39]:
df_empresa3.de_ramo.value_counts()

ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL    150
SERVICOS ADMINISTRATIVOS                              35
SERVICOS DE EDUCACAO                                  22
TRANSPORTE, ARMAZENAGEM E CORREIO                     14
SERVICOS DE SAUDE                                     13
SERVICOS DE ALOJAMENTO/ALIMENTACAO                     5
SERVICOS DE SANEAMENTO BASICO                          5
SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS         5
SERVICOS DIVERSOS                                      4
TELECOM                                                3
SEGUROS, PLANOS DE PREVIDENCIA E PLANOS DE SAUDE       3
SERVICOS FINANCEIROS                                   2
SERVICOS SOCIAIS                                       1
CULTURA, ESPORTE E RECREACAO                           1
ATIVIDADES IMOBILIARIAS                                1
INDUSTRIA DIGITAL                                      1
Name: de_ramo, dtype: int64

In [40]:
le = preprocessing.LabelEncoder()

## Preparando portfolio 1

In [41]:
port_1 = filter_columns(df_empresa1)

In [42]:
#exploracao(port_1)

In [43]:
port_1 = port_1.dropna()
port_1 = port_1.set_index('id')

In [44]:
port_1.shape

(396, 41)

In [45]:
port_1_encode = encoding_obj(port_1, le)
port_1_encode

,fl_optante_simples,fl_optante_simei,nm_micro_regiao,nm_meso_regiao,nu_meses_rescencia,vl_faturamento_estimado_grupo_aux,vl_faturamento_estimado_aux,de_faixa_faturamento_estimado_grupo,de_faixa_faturamento_estimado,de_saude_rescencia,de_saude_tributaria,de_nivel_atividade,sg_uf_matriz,fl_passivel_iss,setor,nm_divisao,fl_simples_irregular,nm_segmento,vl_total_veiculos_pesados_grupo,fl_veiculo,fl_antt,fl_spa,vl_total_veiculos_leves_grupo,dt_situacao,fl_matriz,fl_me,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,idade_empresa_anos,idade_emp_cat,fl_sa,fl_rm,fl_epp,fl_mei,fl_ltda,fl_st_especial,fl_email,fl_telefone,qt_filiais
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
32e5f4e10932153a7ba869cb0386e7e02d49d2461046b866411556d2af150702,0,0,41,3,22.0,1000915.2,210000.0,6,5,0,3,2,3,0,0,0,0,0,0.0,0,0,0,0.0,143,False,False,1,2,1,1,6.586301,3,False,0,False,False,False,False,True,True,4
a95d6f30bba445bd3d6b0c5b36f865b38ec01d1733609095d359649cfedf15d1,1,1,0,8,24.0,50000.0,50000.0,1,0,0,1,2,3,0,0,0,0,0,0.0,0,0,0,0.0,104,True,False,1,2,1,1,8.010959,3,False,1,False,True,False,False,False,False,0
6cb309685cea0b6d2988818792ec2e6fcb2bd02e0afa9e74532d5040fbc933b8,1,1,62,11,26.0,50000.0,50000.0,1,0,0,3,0,5,0,0,0,0,0,0.0,0,0,0,0.0,26,True,False,1,4,1,1,20.863014,4,False,0,False,False,False,False,False,False,0
f72aa7fa6787b0a5a1c88885b6120850df8ee0f71adc251dfe8d321e9e6de7f5,1,0,44,6,23.0,5872824.0,3029140.8,7,1,0,3,0,5,0,0,0,0,0,0.0,0,0,0,0.0,26,True,False,5,4,0,1,18.726027,2,False,1,False,False,False,False,True,True,3
f7e2894dce5dbb49662da50c55bcb96cdc3d34188abfe82d54ab6d94e7244d0c,1,0,26,16,25.0,210000.0,210000.0,8,5,0,1,1,3,0,0,0,0,0,0.0,0,0,0,0.0,154,True,False,1,2,1,1,6.238356,3,False,0,False,False,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0c0b6a530965c03eaebeeb9c21e5d73127f765ce00c70b44e4d3b509b80eca06,0,0,60,2,23.0,210000.0,210000.0,8,5,0,1,0,1,0,0,0,0,0,0.0,0,0,0,0.0,91,True,False,1,1,1,1,8.531507,3,False,0,False,False,False,False,False,False,0
f1c4e9e123c2fa80339ad2a363ba133e4d936e6137d7b4696a83490dad648200,1,0,40,2,48.0,210000.0,210000.0,8,5,0,0,2,1,0,0,0,0,0,0.0,0,0,0,0.0,84,True,False,1,1,1,1,9.191781,3,False,1,False,False,False,False,False,True,0
4e2353206c04c6a8c097252c89f6970594f0796676bba5fceed62603f0acd1ca,0,0,0,8,23.0,210000.0,210000.0,8,5,0,2,2,3,0,1,1,0,1,0.0,0,0,0,0.0,26,True,False,5,2,0,0,27.660274,4,False,1,False,False,False,False,False,False,0
4fbebb5a4ea9d2c5da87f446aff48403f0409e2e8fe381f8bf1e5b47fa426207,0,0,61,4,47.0,210000.0,210000.0,8,5,0,1,2,4,0,0,0,0,0,0.0,0,0,0,0.0,26,True,False,1,3,1,1,31.868493,4,False,1,False,False,False,False,False,False,0
970485e6b8abe52d8fb4e0bf060fb6f0f4f8576cb7583d885a8dcac38f506389,1,1,61,4,22.0,50000.0,50000.0,1,0,0,3,2,4,0,0,0,0,0,0.0,0,0,0,0.0,217,True,False,1,3,1,1,3.994521,0,False,1,False,True,False,False,False,True,0

# Criar modelo de baseline

In [46]:
#market_clean.head()

### Apagando todos os valores nulos

In [47]:
market_clean = market_clean.dropna()
market_clean = market_clean.set_index('id')
market_clean.head()

,fl_optante_simples,fl_optante_simei,nm_micro_regiao,nm_meso_regiao,nu_meses_rescencia,vl_faturamento_estimado_grupo_aux,vl_faturamento_estimado_aux,de_faixa_faturamento_estimado_grupo,de_faixa_faturamento_estimado,de_saude_rescencia,de_saude_tributaria,de_nivel_atividade,sg_uf_matriz,fl_passivel_iss,setor,nm_divisao,fl_simples_irregular,nm_segmento,vl_total_veiculos_pesados_grupo,fl_veiculo,fl_antt,fl_spa,vl_total_veiculos_leves_grupo,dt_situacao,fl_matriz,fl_me,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,idade_empresa_anos,idade_emp_cat,fl_sa,fl_rm,fl_epp,fl_mei,fl_ltda,fl_st_especial,fl_email,fl_telefone,qt_filiais
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
a6984c3ae395090e3bee8ad63c3758b110de096d5d819583a784a113726db849,True,False,NATAL,LESTE POTIGUAR,23.0,3132172.8,3132172.8,"DE R$ 1.500.000,01 A R$ 4.800.000,00","DE R$ 1.500.000,01 A R$ 4.800.000,00",ACIMA DE 1 ANO,VERDE,ALTA,RN,True,CONSTRUÇÃO CIVIL,CONSTRUCAO DE EDIFICIOS,False,CONSTRUCAO,0.0,False,False,False,0.0,2005-03-25,True,False,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,14.457534,10 a 15,False,SIM,False,False,False,False,True,True,0
4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02edc5147bc2a2535b08,True,True,MANAUS,CENTRO AMAZONENSE,26.0,50000.0,50000.0,"ATE R$ 81.000,00","ATE R$ 81.000,00",ACIMA DE 1 ANO,AMARELO,MEDIA,AM,True,SERVIÇO,TRANSPORTE TERRESTRE,False,TRANSPORTE ARMAZENAGEM E CORREIO,0.0,False,False,False,0.0,2011-09-26,True,False,EMPRESARIO INDIVIDUAL,AM,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",7.093151,5 a 10,False,SIM,False,True,False,False,False,True,0
3348900fe63216a439d2e5238c79ddd46ede454df7b9d8c24ac33eb21d4b21ef,True,False,MANAUS,CENTRO AMAZONENSE,26.0,210000.0,210000.0,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",ACIMA DE 1 ANO,AMARELO,MEDIA,AM,True,SERVIÇO,REPARACAO E MANUTENCAO DE EQUIPAMENTOS DE INFO...,False,OUTRAS ATIVIDADES DE SERVICOS,0.0,False,False,False,0.0,2012-04-25,True,False,EMPRESARIO INDIVIDUAL,AM,OUTROS,SERVICOS DIVERSOS,6.512329,5 a 10,False,SIM,False,False,False,False,True,True,0
1f9bcabc9d3173c1fe769899e4fac14b053037b953a1e4b102c769f7611ab29f,True,False,NATAL,LESTE POTIGUAR,27.0,210000.0,210000.0,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",ACIMA DE 1 ANO,VERDE,ALTA,RN,True,SERVIÇO,SERVICOS DE ARQUITETURA E ENGENHARIA TESTES E ...,False,ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS,0.0,False,False,False,0.0,2015-08-17,True,False,EMPRESARIO INDIVIDUAL,RN,OUTROS,"SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS",3.200000,1 a 5,False,SIM,False,False,False,False,True,True,0
529a1f5fc6f88071db7d38492a0ce7c985c77e9b1c3bb62f5bd2ebec4860a392,False,False,PAU DOS FERROS,OESTE POTIGUAR,48.0,210000.0,210000.0,"DE R$ 81.000,01 A R$ 360.000,00","DE R$ 81.000,01 A R$ 360.000,00",ACIMA DE 1 ANO,LARANJA,ALTA,RN,False,INDUSTRIA,FABRICACAO DE PRODUTOS DE MINERAIS NAO METALICOS,False,INDUSTRIAS DE TRANSFORMACAO,0.0,False,False,False,0.0,2005-11-03,True,False,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,QUIMICA-PETROQUIMICA,38.079452,> 20,False,NAO,False,False,False,False,False,False,0

### Verificando os tipos de dados das colunas do dataframe

In [48]:
market_clean.dtypes.value_counts()

object     25
bool        9
float64     6
int64       1
dtype: int64

In [49]:
df_encode = encoding_obj(market_clean, le)

In [50]:
df_encode.head()

,fl_optante_simples,fl_optante_simei,nm_micro_regiao,nm_meso_regiao,nu_meses_rescencia,vl_faturamento_estimado_grupo_aux,vl_faturamento_estimado_aux,de_faixa_faturamento_estimado_grupo,de_faixa_faturamento_estimado,de_saude_rescencia,de_saude_tributaria,de_nivel_atividade,sg_uf_matriz,fl_passivel_iss,setor,nm_divisao,fl_simples_irregular,nm_segmento,vl_total_veiculos_pesados_grupo,fl_veiculo,fl_antt,fl_spa,vl_total_veiculos_leves_grupo,dt_situacao,fl_matriz,fl_me,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,idade_empresa_anos,idade_emp_cat,fl_sa,fl_rm,fl_epp,fl_mei,fl_ltda,fl_st_especial,fl_email,fl_telefone,qt_filiais
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
a6984c3ae395090e3bee8ad63c3758b110de096d5d819583a784a113726db849,1,0,48,6,23.0,3132172.8,3132172.8,2,2,0,4,0,19,1,2,32,0,10,0.0,0,0,0,0.0,2595,True,False,57,4,2,11,14.457534,1,False,1,False,False,False,False,True,True,0
4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02edc5147bc2a2535b08,1,1,43,2,26.0,50000.0,50000.0,1,1,0,0,2,2,1,4,86,0,20,0.0,0,0,0,0.0,4655,True,False,16,1,5,31,7.093151,3,False,1,False,True,False,False,False,True,0
3348900fe63216a439d2e5238c79ddd46ede454df7b9d8c24ac33eb21d4b21ef,1,0,43,2,26.0,210000.0,210000.0,10,10,0,0,2,2,1,4,74,0,17,0.0,0,0,0,0.0,4865,True,False,16,1,5,24,6.512329,3,False,1,False,False,False,False,True,True,0
1f9bcabc9d3173c1fe769899e4fac14b053037b953a1e4b102c769f7611ab29f,1,0,48,6,27.0,210000.0,210000.0,10,10,0,4,0,19,1,4,77,0,8,0.0,0,0,0,0.0,6052,True,False,16,4,5,26,3.200000,0,False,1,False,False,False,False,True,True,0
529a1f5fc6f88071db7d38492a0ce7c985c77e9b1c3bb62f5bd2ebec4860a392,0,0,50,11,48.0,210000.0,210000.0,10,10,0,3,0,19,0,3,55,0,13,0.0,0,0,0,0.0,2787,True,False,57,4,2,17,38.079452,5,False,0,False,False,False,False,False,False,0

In [51]:
df_encode.dtypes.value_counts()

int64      26
bool        9
float64     6
dtype: int64

In [52]:
df_encode.shape

(331157, 41)

In [53]:
df_encode.columns

Index(['fl_optante_simples', 'fl_optante_simei', 'nm_micro_regiao',
       'nm_meso_regiao', 'nu_meses_rescencia',
       'vl_faturamento_estimado_grupo_aux', 'vl_faturamento_estimado_aux',
       'de_faixa_faturamento_estimado_grupo', 'de_faixa_faturamento_estimado',
       'de_saude_rescencia', 'de_saude_tributaria', 'de_nivel_atividade',
       'sg_uf_matriz', 'fl_passivel_iss', 'setor', 'nm_divisao',
       'fl_simples_irregular', 'nm_segmento',
       'vl_total_veiculos_pesados_grupo', 'fl_veiculo', 'fl_antt', 'fl_spa',
       'vl_total_veiculos_leves_grupo', 'dt_situacao', 'fl_matriz', 'fl_me',
       'de_natureza_juridica', 'sg_uf', 'natureza_juridica_macro', 'de_ramo',
       'idade_empresa_anos', 'idade_emp_cat', 'fl_sa', 'fl_rm', 'fl_epp',
       'fl_mei', 'fl_ltda', 'fl_st_especial', 'fl_email', 'fl_telefone',
       'qt_filiais'],
      dtype='object')

## Criando "EDA" com a lib Sweet Viz

In [54]:
# my_report = sv.analyze(df_encode)
# my_report.show_html(filepath='eda.html')

### Criando instância do NearestNeighbors

In [55]:
modelo = NearestNeighbors(n_neighbors=10, algorithm='brute', metric='cosine', n_jobs=-1)

### Treinando modelo

In [56]:
%%time
modelo.fit(df_encode)

CPU times: user 413 ms, sys: 60.3 ms, total: 473 ms
Wall time: 472 ms

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=10)

# ANOTAÇÕES

#### separa o portfolio em treino e teste. Passa o treino como argumento e a partir daí vai ser gerado os leads, e verifica quantos dos leads recomendados existem no teste

In [57]:
X_train, X_test = treino_teste_port(port_1_encode)

In [61]:
%%time
neighbors_list = {}

for row in range(X_train.shape[0]):
    #print(row)
    neighbors_list[row] = modelo.kneighbors(X_train.iloc[[row]].values, n_neighbors=10)

CPU times: user 6min 19s, sys: 48.6 s, total: 7min 8s
Wall time: 54 s

In [70]:
neighbors_list[0]

(array([[3.78152498e-09, 8.50497586e-08, 1.04117236e-07, 1.09990698e-07,
         1.44229347e-07, 1.67833034e-07, 1.69507631e-07, 2.15387289e-07,
         2.61970096e-07, 2.95260275e-07]]),
 array([[162710, 252440, 206407, 255245,  86512, 248662, 189184,  55701,
         191079,  69656]]))

In [62]:
len(neighbors_list[0][1][0])

10

In [71]:
# Da lista de vizinhos, filtrar os clientes pertencentes ao portfólio de entrada.
list_size = len(neighbors_list)
num_neighbors = len(neighbors_list[0][1][0])

neighbors_idx_array = neighbors_list[0][1][0]
neighbors_distance_array = neighbors_list[0][0][0]
np.delete(neighbors_idx_array, [0,1])
np.delete(neighbors_distance_array, [0,1])
for line in range(1,list_size):
    neighbors_idx_array = np.concatenate((neighbors_idx_array, neighbors_list[line][1][0]), axis=None) 
    neighbors_distance_array = np.concatenate((neighbors_distance_array, neighbors_list[line][0][0]), axis=None) 

if len(neighbors_idx_array) != list_size*num_neighbors:
    print("ERROR: Check array size.")
# Temos agora um array unidimensional com os índices dos clientes recomendados)

In [74]:
# Criar um dicionário com o id de origem da requisição, id do vizinho e distância entre eles
dicio = {}
for idx, ind in zip(neighbors_idx_array, range(len(neighbors_idx_array))):
    dicio[ind] = (port_1.iloc[int(ind/10)].name, market_clean.iloc[idx].name,
                  (neighbors_distance_array[ind]))

In [75]:
#Criando um DataFrame com as sugestões.
neig_df = pd.DataFrame.from_dict(dicio,orient='index')
neig_df.rename(columns={0:'id_origin', 1:'id',2:'distance'},inplace = True)
neig_df.set_index('id', inplace=True)

In [76]:
neig_df

,id_origin,distance
id,,
1ccdd1d6035e5a4b8f10d5b2d428be95f3814915bbd4e1f9b6eb0ce2b7293335,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,3.781525e-09
61ede3e056d42d9b17b8f5f33d7c56c3c5c479dca968e5e7a36a9b4bc47ccd54,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,8.504976e-08
a31cb3d1a5bf36e4da8652ae6fc5019803a88437dc54e7271f82870f775c78b3,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,1.041172e-07
2d5a7dc37f6ba7675aa0e5d6b49396d67f3080531701e895ec5cd468f622fa4b,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,1.099907e-07
3859ed0475a3404928aa8c6d260c35a0eb5c3c40815456bbf5497cafcc5c3529,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,1.442293e-07
...,...,...
dae32f3723cb017d485e48ede0c4dd59581ab38dba9788ce2c44a0d23dbf6bb8,b505e0c2ca908276bf09c23f7ef2dc112ac7b10a29e438...,4.482673e-09
fd524ba2430564345b7fa7ede7aae4373136a4c05a0dc3d717665b4d44bbbb64,b505e0c2ca908276bf09c23f7ef2dc112ac7b10a29e438...,4.502342e-09
af9d1719d261294ba544d39f30458f84a818af8d0ab7c360bc54189ca54670c2,b505e0c2ca908276bf09c23f7ef2dc112ac7b10a29e438...,4.572213e-09
b6bd01ef3f89d311eec8e4d777ab58c9f5dc61c547080527ec2cdbc041605a46,b505e0c2ca908276bf09c23f7ef2dc112ac7b10a29e438...,4.598940e-09
c5adc8ffede3c5125c53182907747e451e8473a2dc3e560cd82f1efcd1dc94b9,b505e0c2ca908276bf09c23f7ef2dc112ac7b10a29e438...,4.634867e-09

In [77]:
# Identificando os conflitos e removendo da lista de sugestões.
conflicts = neig_df.merge(X_train, how='inner',left_index=True,right_index=True)
suggestion_with_conflicts = neig_df.merge(market_clean, how='left',left_index=True,right_index=True)

suggestions = suggestion_with_conflicts.drop(conflicts.index)

In [78]:
# Verificar número de hits (quantas sugestões são parte de um conjunto de teste)
def count_hits_in_suggestion(df_suggestions, df_X_test): #suggestions e X_test são dataframes
    X_list = df_X_test.index.to_list()
    hits = 0
    for sugg in df_suggestions.index.to_list():
        hits = hits + X_list.count(sugg)
    return hits

In [79]:
our_hits = count_hits_in_suggestion(suggestions, X_test)

In [80]:
our_hits

0

In [81]:
# Compara com sorteio aleatório (random picking) da base market

n_picking = len(suggestions) # quantidade de sugestões a sortear

# Simulação de Monte Carlo, ou seja, sortear um conjunto várias vezes e depois fazer a média
monte_carlo_size = 500
num_hits = int(0)
for k in range(monte_carlo_size):
    random_suggestion = df_encode.sample(n = n_picking)
    num_hits = num_hits + count_hits_in_suggestion(random_suggestion, X_test)
mean_num_hits = num_hits / monte_carlo_size

In [82]:
print(f'Number of hits in our suggestion: {our_hits}.')
print(f'They represent {100*our_hits/len(X_test):.2f}% of the test size.\n')

print(f'For random suggestion, we found an average of {mean_num_hits:.2f} hits.')
print(f'They represent {100*mean_num_hits/len(X_test):.2f}% of the test size.')

Number of hits in our suggestion: 0.
They represent 0.00% of the test size.

For random suggestion, we found an average of 1.00 hits.
They represent 0.84% of the test size.